name-template: 'v$NEXT_PATCH_VERSION' # defaults to patch version
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 💥 Breaking Changes
    label: 'BREAKING CHANGE'

  - title: ✨ Features
    label: 'feat'

  - title: 🐛 Bug Fixes
    label: 'fix'

  - title: 🚀 Improvements
    label: 'perf'

  - title: 🔧 Code Improvements
    label: 'refactor'

  - title: 🚧 Maintenance
    label: 'chore'

  - title: 👷 CI/CD
    label: 'ci'

  - title: 🔩 Build
    label: 'build'

  - title: 💯 Tests
    label: 'test'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
