language: go

go:
  - 1.11.x

env:
  global:
  - DOCKER_REGISTRY=registry.gahmen.tech
  - IMAGE_NAME=${DOCKER_REGISTRY}/l/nomad-parametric-autoscaler
  - GITHUB_USER=datagovsg
  - GITHUB_REPONAME=nomad-parametric-autoscaler


script: 
  - go mod download
  - go test -v ./...

deploy:
  provider: releases
  skip_cleanup: true # Important, otherwise the build output would be purged.
  script:
    - docker build . -t ${IMAGE_NAME}:${TRAVIS_BRANCH}
    - docker login ${DOCKER_REGISTRY} -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    - docker push ${IMAGE_NAME}:${TRAVIS_BRANCH}
  on:
    tags: true # The deployment happens only if the commit has a tag.