env:
  global:
  - IMAGE_NAME=${DOCKER_REGISTRY}/dsaid/datagovsg/nopas
  - UI_IMAGE_NAME=${DOCKER_REGISTRY}/dsaid/datagovsg/nopas-ui

matrix:
  include:
    - language: go
      go: 1.11.x      
      script: 
        - go test -v ./...
      before_deploy:
        - docker login ${DOCKER_REGISTRY} -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker build . -t ${IMAGE_NAME}:${TRAVIS_TAG}
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - docker push ${IMAGE_NAME}:${TRAVIS_TAG}
        on:
          tags: true

    - language: node_js
      node_js: "10"
      install:
        - cd ui/
        - npm install
      script:
        - npm run lint && npm test
      before_deploy:
        - docker login ${DOCKER_REGISTRY} -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker build . -t ${UI_IMAGE_NAME}:${TRAVIS_TAG}
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - docker push ${UI_IMAGE_NAME}:${TRAVIS_TAG}
        on:
          tags: true
