version: '2.2'
services:
  nopas:
    build: .
    ports:
      - '8080:8080'
    restart: on-failure:5
    security_opt:
      - 'no-new-privileges'
    pids_limit: 100
    tmpfs: ['/tmp']
    depends_on: 
      - db
    env_file:
      - .env
    environment:
      GIN_MODE: release
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_HOST: db # use localhost if running the binary in terminal
      POSTGRES_PORT: 5432

  ui:
    build: ./ui
    depends_on:
      - nopas
    environment:
      PORT: 5000
      REACT_APP_NOPAS_ENDPOINT: "http://localhost:8080"
    ports:
      - 5000:5000
    
  db:
    image: postgres:9.6.11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
