version: '2.2'
services:
  nopas:
    build: .
    ports:
      - '8080:8080'
    restart: on-failure:5
    security_opt:
      - 'no-new-privileges'
    pids_limit: 100
    tmpfs: ['/tmp']
    depends_on: 
      - db
    environment:
      GIN_MODE: release
      ASG_ID: ""
      ASG_SECRET: ""
      VAULT_ADDR: ""
      VAULT_TOKEN: ""
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  ui:
    build: ./ui
    depends_on:
      - nopas
    environment:
      PORT: 5000
      REACT_APP_NOPAS_ENDPOINT: "http://localhost:8080"
    ports:
      - 5000:5000
    
  db:
    image: postgres:9.6.11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: docker
